### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by DemHydraz** [TARDIX/Kernel#4]
###Virtual File System
----------------------------
- [ ] Inode table creation
- [ ] Inode table manipulation
- [ ] Symbolic/ Hard Links
- [ ] Sockets
- [ ] Mounting
- [ ] File System in Userland (FUSE) Support

**Comment by DemHydraz** [comment]
Multi-User Support
------------------------
- [ ] Logging in
- [ ] Logging out
- [ ] Permissions
  - [ ] Inode permission metadata manipulation

**Comment by TheOnlyCreator** [comment]
I've got an idea for the filesystem.
Maybe it could work like this: a predefined amount of bytes in the beginning contain the lenght of the metadata. The metadata is structured like this: one byte for permission type + if the permission is that only some people can modify the file/dir then 2 bytes per program allowed to modify it. 2 bytes because I doubt there will be more than 65536 apps

**Comment by DemHydraz** [comment]
Sandboxing
----------------

- [ ] System calls
  - [ ] Kernel mode traps
- [x] VMMs to manage System calls
  
CLARTI
-----------

- [ ] Finish the specification
  - [x] Basic I/O
  - [  ] File I/O
  - [x] Asynchronous I/O
  - [  ] Framebuffer
  - [  ] Program Spawning
         Partially implemented with the _exec_ and _sexec_ system API calls.

**Comment by DemHydraz** [comment]
@TheOnlyCreator: Your idea is very good. However, the _app-centric_ system most operating systems expose, in TARDIX, is completely implementation-dependant. 
That is why, permissions in the file system will be implemented not in the kernel, but in the distribuition.   
That's the core feature of TARDIX:  
  Simplicity and Modularity.

**Comment by RainbowDashDC** [comment]
# Libnet

- [ ] support TCP like calls by waiting for a response
- [ ] Finish implementing the libnet specs in :recieve()
- [ ] Make libnet less reliant on the Host OS, handing control over to the daemon.

**Comment by FlareHAX0R** [comment]
Cats. We need CATS.

**Comment by DemHydraz** [comment]
huh?

**Comment by SquidDev** [comment]
I think he means [this](https://en.wikipedia.org/wiki/Canon_Cat).

**Comment by FlareHAX0R** [comment]
It was a joke.

**Comment by DemHydraz** [comment]
@SquidDev I was assuming `cat(1)`.
